2021-09-01 01:49:44,344 INFO    MainThread:21564 [wandb_setup.py:_flush():69] setting env: {}
2021-09-01 01:49:44,345 INFO    MainThread:21564 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-01 01:49:44,345 INFO    MainThread:21564 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-01 01:49:44,345 INFO    MainThread:21564 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210901_014944-2p7ria01\logs\debug.log
2021-09-01 01:49:44,346 INFO    MainThread:21564 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210901_014944-2p7ria01\logs\debug-internal.log
2021-09-01 01:49:44,347 INFO    MainThread:21564 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000028553F0BA90>
2021-09-01 01:49:44,383 INFO    MainThread:21564 [wandb_init.py:init():375] calling init triggers
2021-09-01 01:49:44,384 INFO    MainThread:21564 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-01 01:49:44,384 INFO    MainThread:21564 [wandb_init.py:init():424] starting backend
2021-09-01 01:49:44,384 INFO    MainThread:21564 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-01 01:49:44,390 INFO    MainThread:21564 [backend.py:ensure_launched():135] starting backend process...
2021-09-01 01:49:44,516 INFO    MainThread:21564 [backend.py:ensure_launched():139] started backend process with pid: 16920
2021-09-01 01:49:44,517 INFO    MainThread:21564 [wandb_init.py:init():429] backend started and connected
2021-09-01 01:49:44,518 INFO    MainThread:21564 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-09-01 01:49:44,518 INFO    MainThread:21564 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-01 01:49:44,518 INFO    MainThread:21564 [wandb_init.py:init():477] updated telemetry
2021-09-01 01:49:44,519 INFO    MainThread:21564 [wandb_init.py:init():500] communicating current version
2021-09-01 01:49:46,663 INFO    MainThread:21564 [wandb_init.py:init():505] got version response 
2021-09-01 01:49:46,663 INFO    MainThread:21564 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-01 01:50:16,663 INFO    MainThread:21564 [interface.py:_communicate_run():651] couldn't get run from backend
2021-09-01 01:50:16,663 ERROR   MainThread:21564 [wandb_init.py:init():518] backend process timed out
2021-09-01 01:50:16,663 ERROR   MainThread:21564 [wandb_init.py:init():527] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-09-01 01:52:16,526 INFO    MainThread:21564 [wandb_init.py:teardown():194] tearing down wandb.init
