2021-09-13 19:43:48,800 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting env: {}
2021-09-13 19:43:48,800 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-13 19:43:48,800 INFO    MainThread:9504 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210913_194348-l4a64aos\logs\debug.log
2021-09-13 19:43:48,801 INFO    MainThread:9504 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210913_194348-l4a64aos\logs\debug-internal.log
2021-09-13 19:43:48,802 INFO    MainThread:9504 [wandb_init.py:init():375] calling init triggers
2021-09-13 19:43:48,802 INFO    MainThread:9504 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-13 19:43:48,824 INFO    MainThread:9504 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 3202v2y4
2021-09-13 19:43:48,824 INFO    MainThread:9504 [wandb_run.py:finish():1271] finishing run khushal/2final-weather-recognization/3202v2y4
2021-09-13 19:43:48,826 INFO    MainThread:9504 [jupyter.py:save_history():353] not saving jupyter history
2021-09-13 19:43:48,826 INFO    MainThread:9504 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-13 19:43:48,826 INFO    MainThread:9504 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-09-13 19:43:48,826 INFO    MainThread:9504 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-13 19:43:48,827 INFO    MainThread:9504 [wandb_run.py:_restore():1543] restore
2021-09-13 19:43:49,008 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 483
}

2021-09-13 19:43:49,800 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 483
}

2021-09-13 19:43:50,146 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21067
}

2021-09-13 19:43:50,248 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21067
}

2021-09-13 19:43:50,350 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21067
}

2021-09-13 19:43:50,452 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21067
}

2021-09-13 19:43:50,553 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21067
}

2021-09-13 19:43:50,654 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21067
}

2021-09-13 19:43:50,755 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21067
}

2021-09-13 19:43:50,856 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21067
}

2021-09-13 19:43:50,957 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21067
}

2021-09-13 19:43:51,058 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21067
  total_bytes: 21067
}

2021-09-13 19:43:51,160 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21067
  total_bytes: 21067
}

2021-09-13 19:43:51,261 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21067
  total_bytes: 21067
}

2021-09-13 19:43:51,363 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21067
  total_bytes: 21067
}

2021-09-13 19:43:51,464 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21067
  total_bytes: 21067
}

2021-09-13 19:43:51,565 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21067
  total_bytes: 21067
}

2021-09-13 19:43:51,666 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21067
  total_bytes: 21067
}

2021-09-13 19:43:51,767 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21067
  total_bytes: 21067
}

2021-09-13 19:43:52,832 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21067
  total_bytes: 21067
}

2021-09-13 19:43:52,935 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21067
  total_bytes: 21067
}

2021-09-13 19:43:54,305 INFO    MainThread:9504 [wandb_run.py:_show_files():1915] logging synced files
2021-09-13 19:43:54,310 INFO    MainThread:9504 [wandb_init.py:init():424] starting backend
2021-09-13 19:43:54,311 INFO    MainThread:9504 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-13 19:43:54,315 INFO    MainThread:9504 [backend.py:ensure_launched():135] starting backend process...
2021-09-13 19:43:54,417 INFO    MainThread:9504 [backend.py:ensure_launched():139] started backend process with pid: 8984
2021-09-13 19:43:54,418 INFO    MainThread:9504 [wandb_init.py:init():429] backend started and connected
2021-09-13 19:43:54,419 INFO    MainThread:9504 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-13 19:43:54,419 INFO    MainThread:9504 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-13 19:43:54,419 INFO    MainThread:9504 [wandb_init.py:init():477] updated telemetry
2021-09-13 19:43:54,420 INFO    MainThread:9504 [wandb_init.py:init():500] communicating current version
2021-09-13 19:43:57,551 INFO    MainThread:9504 [wandb_init.py:init():505] got version response 
2021-09-13 19:43:57,551 INFO    MainThread:9504 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-13 19:43:58,117 INFO    MainThread:9504 [wandb_init.py:init():540] starting run threads in backend
2021-09-13 19:44:03,131 INFO    MainThread:9504 [wandb_run.py:_console_start():1601] atexit reg
2021-09-13 19:44:03,132 INFO    MainThread:9504 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-13 19:44:03,133 INFO    MainThread:9504 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-13 19:44:03,136 INFO    MainThread:9504 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-13 19:44:03,136 INFO    MainThread:9504 [wandb_init.py:init():565] run started, returning control to user process
2021-09-13 19:44:21,393 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting env: {}
2021-09-13 19:44:21,393 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-13 19:44:21,394 INFO    MainThread:9504 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210913_194421-3fi6mba6\logs\debug.log
2021-09-13 19:44:21,394 INFO    MainThread:9504 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210913_194421-3fi6mba6\logs\debug-internal.log
2021-09-13 19:44:21,395 INFO    MainThread:9504 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001D892B7C280>
2021-09-13 19:44:21,429 INFO    MainThread:9504 [wandb_init.py:init():375] calling init triggers
2021-09-13 19:44:21,429 INFO    MainThread:9504 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-13 19:44:21,430 INFO    MainThread:9504 [wandb_init.py:init():395] re-initializing run, found existing run on stack: l4a64aos
2021-09-13 19:44:21,430 INFO    MainThread:9504 [wandb_run.py:finish():1271] finishing run khushal/2final-weather-recognization/l4a64aos
