2021-11-08 15:52:58,264 INFO    MainThread:12548 [wandb_setup.py:_flush():71] setting env: {}
2021-11-08 15:52:58,264 INFO    MainThread:12548 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-08 15:52:58,264 INFO    MainThread:12548 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-08 15:52:58,264 INFO    MainThread:12548 [wandb_init.py:_log_setup():357] Logging user logs to D:\5th sem project\wandb\run-20211108_155258-18dcn2qd\logs\debug.log
2021-11-08 15:52:58,264 INFO    MainThread:12548 [wandb_init.py:_log_setup():358] Logging internal logs to D:\5th sem project\wandb\run-20211108_155258-18dcn2qd\logs\debug-internal.log
2021-11-08 15:52:58,264 INFO    MainThread:12548 [wandb_init.py:_jupyter_setup():307] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001B17676E8E0>
2021-11-08 15:52:58,264 INFO    MainThread:12548 [wandb_init.py:init():390] calling init triggers
2021-11-08 15:52:58,264 INFO    MainThread:12548 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-11-08 15:52:58,264 INFO    MainThread:12548 [wandb_init.py:init():435] starting backend
2021-11-08 15:52:58,264 INFO    MainThread:12548 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2021-11-08 15:52:58,279 INFO    MainThread:12548 [backend.py:ensure_launched():199] starting backend process...
2021-11-08 15:52:58,373 INFO    MainThread:12548 [backend.py:ensure_launched():204] started backend process with pid: 8304
2021-11-08 15:52:58,373 INFO    MainThread:12548 [wandb_init.py:init():444] backend started and connected
2021-11-08 15:52:58,373 INFO    MainThread:12548 [wandb_run.py:_label_probe_notebook():866] probe notebook
2021-11-08 15:52:58,373 INFO    MainThread:12548 [wandb_run.py:_label_probe_notebook():876] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-11-08 15:52:58,373 INFO    MainThread:12548 [wandb_init.py:init():503] updated telemetry
2021-11-08 15:52:58,373 INFO    MainThread:12548 [wandb_init.py:init():533] communicating current version
2021-11-08 15:53:00,448 INFO    MainThread:12548 [wandb_init.py:init():538] got version response 
2021-11-08 15:53:00,448 INFO    MainThread:12548 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-08 15:53:30,453 INFO    MainThread:12548 [interface_queue.py:_communicate_run():336] couldn't get run from backend
2021-11-08 15:53:30,453 ERROR   MainThread:12548 [wandb_init.py:init():553] backend process timed out
2021-11-08 15:53:30,453 ERROR   MainThread:12548 [wandb_init.py:init():562] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
