2021-09-04 14:22:53,596 INFO    MainThread:2968 [wandb_setup.py:_flush():69] setting env: {}
2021-09-04 14:22:53,597 INFO    MainThread:2968 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:22:53,597 INFO    MainThread:2968 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:22:53,597 INFO    MainThread:2968 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210904_142253-3t30k1hn\logs\debug.log
2021-09-04 14:22:53,598 INFO    MainThread:2968 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210904_142253-3t30k1hn\logs\debug-internal.log
2021-09-04 14:22:53,598 INFO    MainThread:2968 [wandb_init.py:init():375] calling init triggers
2021-09-04 14:22:53,630 INFO    MainThread:2968 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-04 14:22:53,630 INFO    MainThread:2968 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 3d0tgi1n
2021-09-04 14:22:53,630 INFO    MainThread:2968 [wandb_run.py:finish():1254] finishing run khushal/final-weather-recognization/3d0tgi1n
2021-09-04 14:22:53,631 INFO    MainThread:2968 [jupyter.py:save_history():339] not saving jupyter history
2021-09-04 14:22:53,631 INFO    MainThread:2968 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-09-04 14:22:53,631 INFO    MainThread:2968 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-09-04 14:22:53,631 INFO    MainThread:2968 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-09-04 14:22:53,632 INFO    MainThread:2968 [wandb_run.py:_restore():1526] restore
2021-09-04 14:22:54,641 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-04 14:22:55,315 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-04 14:22:56,170 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19638
}

2021-09-04 14:22:56,273 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19665
}

2021-09-04 14:22:56,376 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19665
}

2021-09-04 14:22:56,477 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19665
}

2021-09-04 14:22:56,578 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19665
}

2021-09-04 14:22:56,686 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19665
}

2021-09-04 14:22:56,790 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19665
}

2021-09-04 14:22:56,891 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19665
}

2021-09-04 14:22:56,993 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19665
  total_bytes: 19665
}

2021-09-04 14:22:57,096 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19665
  total_bytes: 19665
}

2021-09-04 14:22:57,197 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19665
  total_bytes: 19665
}

2021-09-04 14:22:57,298 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19665
  total_bytes: 19665
}

2021-09-04 14:22:57,400 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19665
  total_bytes: 19665
}

2021-09-04 14:22:57,501 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19665
  total_bytes: 19665
}

2021-09-04 14:22:57,602 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19665
  total_bytes: 19665
}

2021-09-04 14:22:58,003 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19665
  total_bytes: 19665
}

2021-09-04 14:22:58,106 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19665
  total_bytes: 19665
}

2021-09-04 14:22:59,439 INFO    MainThread:2968 [wandb_run.py:_show_files():1898] logging synced files
2021-09-04 14:22:59,444 INFO    MainThread:2968 [wandb_init.py:init():424] starting backend
2021-09-04 14:22:59,445 INFO    MainThread:2968 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-04 14:22:59,449 INFO    MainThread:2968 [backend.py:ensure_launched():135] starting backend process...
2021-09-04 14:22:59,574 INFO    MainThread:2968 [backend.py:ensure_launched():139] started backend process with pid: 21016
2021-09-04 14:22:59,575 INFO    MainThread:2968 [wandb_init.py:init():429] backend started and connected
2021-09-04 14:22:59,576 INFO    MainThread:2968 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-09-04 14:22:59,576 INFO    MainThread:2968 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-04 14:22:59,576 INFO    MainThread:2968 [wandb_init.py:init():477] updated telemetry
2021-09-04 14:22:59,577 INFO    MainThread:2968 [wandb_init.py:init():500] communicating current version
2021-09-04 14:23:02,904 INFO    MainThread:2968 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-04 14:23:02,905 INFO    MainThread:2968 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-04 14:23:03,821 INFO    MainThread:2968 [wandb_init.py:init():540] starting run threads in backend
2021-09-04 14:23:08,832 INFO    MainThread:2968 [wandb_run.py:_console_start():1584] atexit reg
2021-09-04 14:23:08,833 INFO    MainThread:2968 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-09-04 14:23:08,833 INFO    MainThread:2968 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-09-04 14:23:08,835 INFO    MainThread:2968 [wandb_run.py:_redirect():1519] Redirects installed.
2021-09-04 14:23:08,835 INFO    MainThread:2968 [wandb_init.py:init():565] run started, returning control to user process
2021-09-04 14:24:25,891 INFO    MainThread:2968 [wandb_setup.py:_flush():69] setting env: {}
2021-09-04 14:24:25,891 INFO    MainThread:2968 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:24:25,892 INFO    MainThread:2968 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:24:25,892 INFO    MainThread:2968 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210904_142425-3tn899r5\logs\debug.log
2021-09-04 14:24:25,892 INFO    MainThread:2968 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210904_142425-3tn899r5\logs\debug-internal.log
2021-09-04 14:24:25,893 INFO    MainThread:2968 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001FA43BAE100>
2021-09-04 14:24:25,903 INFO    MainThread:2968 [wandb_init.py:init():375] calling init triggers
2021-09-04 14:24:25,903 INFO    MainThread:2968 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-04 14:24:25,903 INFO    MainThread:2968 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 3t30k1hn
2021-09-04 14:24:25,904 INFO    MainThread:2968 [wandb_run.py:finish():1254] finishing run khushal/final-weather-recognization/3t30k1hn
