2021-08-26 20:06:59,443 INFO    MainThread:14028 [internal.py:wandb_internal():86] W&B internal server running at pid: 14028, started at: 2021-08-26 20:06:59.433721
2021-08-26 20:06:59,445 DEBUG   HandlerThread:14028 [handler.py:handle_request():128] handle_request: check_version
2021-08-26 20:06:59,446 INFO    WriterThread:14028 [datastore.py:open_for_write():77] open: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\run-2td2fkr6.wandb
2021-08-26 20:06:59,450 DEBUG   SenderThread:14028 [sender.py:send():182] send: header
2021-08-26 20:06:59,450 DEBUG   SenderThread:14028 [sender.py:send_request():196] send_request: check_version
2021-08-26 20:07:04,187 DEBUG   SenderThread:14028 [sender.py:send():182] send: run
2021-08-26 20:07:06,020 INFO    SenderThread:14028 [dir_watcher.py:__init__():168] watching files in: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files
2021-08-26 20:07:06,020 INFO    SenderThread:14028 [sender.py:_start_run_threads():740] run started: 2td2fkr6 with start time 1629988617
2021-08-26 20:07:06,020 DEBUG   SenderThread:14028 [sender.py:send():182] send: summary
2021-08-26 20:07:06,020 DEBUG   HandlerThread:14028 [handler.py:handle_request():128] handle_request: run_start
2021-08-26 20:07:06,021 INFO    SenderThread:14028 [sender.py:_save_file():873] saving file wandb-summary.json with policy end
2021-08-26 20:07:07,030 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_created():216] file/dir created: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\wandb-summary.json
2021-08-26 20:07:10,040 DEBUG   HandlerThread:14028 [meta.py:__init__():39] meta init
2021-08-26 20:07:10,040 DEBUG   HandlerThread:14028 [meta.py:__init__():53] meta init done
2021-08-26 20:07:10,040 DEBUG   HandlerThread:14028 [meta.py:probe():210] probe
2021-08-26 20:07:10,047 DEBUG   HandlerThread:14028 [meta.py:_save_pip():57] save pip
2021-08-26 20:07:10,050 DEBUG   HandlerThread:14028 [meta.py:_save_pip():71] save pip done
2021-08-26 20:07:10,050 DEBUG   HandlerThread:14028 [meta.py:_save_conda():78] save conda
2021-08-26 20:07:11,029 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_created():216] file/dir created: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\conda-environment.yaml
2021-08-26 20:07:11,030 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_created():216] file/dir created: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\requirements.txt
2021-08-26 20:07:12,031 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_created():216] file/dir created: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:14,046 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:16,062 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:18,067 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:20,070 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:22,080 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:24,115 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:26,132 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:28,141 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:29,162 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:31,205 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:33,216 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:35,238 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:37,262 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:39,273 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:41,295 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:43,320 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:45,335 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:47,339 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:49,353 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:51,361 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:53,366 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:55,369 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:57,403 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\conda-environment.yaml
2021-08-26 20:07:57,404 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:07:57,871 DEBUG   HandlerThread:14028 [meta.py:_save_conda():86] save conda done
2021-08-26 20:07:57,872 DEBUG   HandlerThread:14028 [meta.py:probe():252] probe done
2021-08-26 20:07:57,879 DEBUG   HandlerThread:14028 [handler.py:handle_request():128] handle_request: stop_status
2021-08-26 20:07:57,880 DEBUG   SenderThread:14028 [sender.py:send_request():196] send_request: stop_status
2021-08-26 20:07:58,406 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_created():216] file/dir created: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\wandb-metadata.json
2021-08-26 20:07:58,881 DEBUG   SenderThread:14028 [sender.py:send():182] send: history
2021-08-26 20:07:58,882 DEBUG   SenderThread:14028 [sender.py:send():182] send: summary
2021-08-26 20:07:58,885 INFO    SenderThread:14028 [sender.py:_save_file():873] saving file wandb-summary.json with policy end
2021-08-26 20:07:58,886 DEBUG   SenderThread:14028 [sender.py:send():182] send: stats
2021-08-26 20:07:58,887 DEBUG   SenderThread:14028 [sender.py:send():182] send: files
2021-08-26 20:07:58,887 INFO    SenderThread:14028 [sender.py:_save_file():873] saving file wandb-metadata.json with policy now
2021-08-26 20:07:59,414 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\wandb-summary.json
2021-08-26 20:07:59,415 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:00,731 INFO    Thread-11 :14028 [upload_job.py:push():137] Uploaded file C:\Users\HP\AppData\Local\Temp\tmpzw60qx42wandb\m0d86rh3-wandb-metadata.json
2021-08-26 20:08:01,424 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:03,455 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:05,458 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:07,471 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:09,499 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:11,510 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:13,528 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:13,883 DEBUG   HandlerThread:14028 [handler.py:handle_request():128] handle_request: stop_status
2021-08-26 20:08:13,883 DEBUG   SenderThread:14028 [sender.py:send_request():196] send_request: stop_status
2021-08-26 20:08:15,547 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:17,574 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:18,130 DEBUG   SenderThread:14028 [sender.py:send():182] send: stats
2021-08-26 20:08:19,582 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:21,606 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:23,618 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:25,664 INFO    Thread-8  :14028 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log
2021-08-26 20:08:29,825 DEBUG   HandlerThread:14028 [handler.py:handle_request():128] handle_request: stop_status
2021-08-26 20:08:29,827 DEBUG   SenderThread:14028 [sender.py:send_request():196] send_request: stop_status
2021-08-26 20:08:52,994 WARNING MainThread:14028 [internal.py:is_dead():364] Internal process exiting, parent pid 14268 disappeared
2021-08-26 20:08:52,994 ERROR   MainThread:14028 [internal.py:wandb_internal():141] Internal process shutdown.
2021-08-26 20:08:53,118 INFO    SenderThread:14028 [sender.py:finish():979] shutting down sender
2021-08-26 20:08:53,118 INFO    SenderThread:14028 [dir_watcher.py:finish():282] shutting down directory watcher
2021-08-26 20:08:53,118 INFO    HandlerThread:14028 [handler.py:finish():677] shutting down handler
2021-08-26 20:08:53,522 INFO    WriterThread:14028 [datastore.py:close():281] close: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\run-2td2fkr6.wandb
2021-08-26 20:08:53,800 INFO    SenderThread:14028 [dir_watcher.py:finish():312] scan: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files
2021-08-26 20:08:53,801 INFO    SenderThread:14028 [dir_watcher.py:finish():318] scan save: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\conda-environment.yaml conda-environment.yaml
2021-08-26 20:08:53,802 INFO    SenderThread:14028 [dir_watcher.py:finish():318] scan save: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\config.yaml config.yaml
2021-08-26 20:08:53,804 INFO    SenderThread:14028 [dir_watcher.py:finish():318] scan save: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\output.log output.log
2021-08-26 20:08:53,819 INFO    SenderThread:14028 [dir_watcher.py:finish():318] scan save: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\requirements.txt requirements.txt
2021-08-26 20:08:53,824 INFO    SenderThread:14028 [dir_watcher.py:finish():318] scan save: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\wandb-metadata.json wandb-metadata.json
2021-08-26 20:08:53,825 INFO    SenderThread:14028 [dir_watcher.py:finish():318] scan save: F:\5th sem project\wandb\run-20210826_200641-2td2fkr6\files\wandb-summary.json wandb-summary.json
2021-08-26 20:08:53,840 INFO    SenderThread:14028 [file_pusher.py:finish():177] shutting down file pusher
2021-08-26 20:08:53,845 INFO    SenderThread:14028 [file_pusher.py:join():182] waiting for file pusher
2021-08-27 08:42:43,862 WARNING FileStreamThread:14028 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/pipweather-recognization/2td2fkr6/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002502432E970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002501F43B250>>, args: ('https://api.wandb.ai/files/khushal/pipweather-recognization/2td2fkr6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': ['wandb-metadata.json']}}
2021-08-27 08:42:44,944 ERROR   Thread-16 :14028 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\HP\anaconda3\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000025026C57A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025026C57A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025026C57A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2021-08-27 08:42:46,073 WARNING FileStreamThread:14028 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/pipweather-recognization/2td2fkr6/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025026C57B80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002501F43B250>>, args: ('https://api.wandb.ai/files/khushal/pipweather-recognization/2td2fkr6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': ['wandb-metadata.json']}}
2021-08-27 08:42:50,484 WARNING FileStreamThread:14028 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/pipweather-recognization/2td2fkr6/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025026C57E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002501F43B250>>, args: ('https://api.wandb.ai/files/khushal/pipweather-recognization/2td2fkr6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': ['wandb-metadata.json']}}
2021-08-27 08:43:00,308 WARNING FileStreamThread:14028 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/pipweather-recognization/2td2fkr6/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025026C57F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002501F43B250>>, args: ('https://api.wandb.ai/files/khushal/pipweather-recognization/2td2fkr6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': ['wandb-metadata.json']}}
2021-08-27 09:38:58,894 WARNING FileStreamThread:14028 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/pipweather-recognization/2td2fkr6/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025026C57E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002501F43B250>>, args: ('https://api.wandb.ai/files/khushal/pipweather-recognization/2td2fkr6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': ['wandb-metadata.json']}}
2021-08-27 09:39:31,457 WARNING FileStreamThread:14028 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/pipweather-recognization/2td2fkr6/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025026C57A30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002501F43B250>>, args: ('https://api.wandb.ai/files/khushal/pipweather-recognization/2td2fkr6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': ['wandb-metadata.json']}}
2021-08-27 09:40:43,728 WARNING FileStreamThread:14028 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/pipweather-recognization/2td2fkr6/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025026C57790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000002501F43B250>>, args: ('https://api.wandb.ai/files/khushal/pipweather-recognization/2td2fkr6/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': ['wandb-metadata.json']}}
