2021-08-18 16:21:22,144 INFO    MainThread:11320 [wandb_setup.py:_flush():69] setting env: {}
2021-08-18 16:21:22,145 INFO    MainThread:11320 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 16:21:22,146 INFO    MainThread:11320 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210818_162122-3aue8pu8\logs\debug.log
2021-08-18 16:21:22,146 INFO    MainThread:11320 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210818_162122-3aue8pu8\logs\debug-internal.log
2021-08-18 16:21:22,148 INFO    MainThread:11320 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001B39C01AA60>
2021-08-18 16:21:22,149 INFO    MainThread:11320 [wandb_init.py:init():375] calling init triggers
2021-08-18 16:21:22,149 INFO    MainThread:11320 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-18 16:21:22,149 INFO    MainThread:11320 [wandb_init.py:init():424] starting backend
2021-08-18 16:21:22,150 INFO    MainThread:11320 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-18 16:21:22,167 INFO    MainThread:11320 [backend.py:ensure_launched():135] starting backend process...
2021-08-18 16:21:22,359 INFO    MainThread:11320 [backend.py:ensure_launched():139] started backend process with pid: 8904
2021-08-18 16:21:22,361 INFO    MainThread:11320 [wandb_init.py:init():429] backend started and connected
2021-08-18 16:21:22,362 INFO    MainThread:11320 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-18 16:21:22,365 INFO    MainThread:11320 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-18 16:21:22,366 INFO    MainThread:11320 [wandb_init.py:init():477] updated telemetry
2021-08-18 16:21:22,367 INFO    MainThread:11320 [wandb_init.py:init():500] communicating current version
2021-08-18 16:21:25,000 INFO    MainThread:11320 [wandb_init.py:init():505] got version response 
2021-08-18 16:21:25,001 INFO    MainThread:11320 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-18 16:21:55,001 INFO    MainThread:11320 [interface.py:_communicate_run():651] couldn't get run from backend
2021-08-18 16:21:55,001 ERROR   MainThread:11320 [wandb_init.py:init():518] backend process timed out
2021-08-18 16:21:55,001 ERROR   MainThread:11320 [wandb_init.py:init():527] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-08-18 16:21:56,006 WARNING MainThread:11320 [wandb_init.py:init():795] interrupted
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 775, in init
    run = wi.init()
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 531, in init
    backend.cleanup()
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\sdk\backend\backend.py", line 167, in cleanup
    self.interface.join()
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\sdk\interface\interface.py", line 833, in join
    self._router.join()
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\sdk\interface\interface.py", line 129, in join
    self._thread.join()
  File "C:\Users\HP\anaconda3\lib\threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "C:\Users\HP\anaconda3\lib\threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
